version: '3'
services:
  web:
    build: .
    ports:
    - 8080:8080
    - 8081:8081
    - 8082:8082
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      FUSIC_YOUTUBE_KEY:
      HASURA_GRAPHQL_ADMIN_SECRET:
  postgres:
    image: postgres
    volumes:
    - db:/var/lib/postgresql/data
volumes:
  db:
